apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Reminder
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: Reminder
    spec:
      containers:
      - name: Reminder
        image: registry.gitlab.com/smelveettil/Reminder
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com